### ISSUE TITLE
How do I show truncated text on hover using angular-tree-component?

### ISSUE THREAD

**Issue by Pradhyo** [500tech/angular-tree-component#757]
I need to limit the width of the angular-tree-component - this results in some nodes having text bigger than the width. I'm truncating this text but would like it to expand on hover in a single line.

Here's the behavior I want (hover over any node to see full text appear) - https://stackblitz.com/edit/angular-eqhwwm?file=src%2Fstyles.css But since I am using `position: fixed`, scrolling the page a little bit and hovering over it makes the node appear where it would have been without scrolling.

I have this working code to display truncated text across lines but the requirement is to have it show up on the same line

```css
.node-content-wrapper:hover {
  text-overflow: clip;
  white-space: normal;
  word-break: break-word;
}
```
